### ISSUE TITLE
AttributeError after upgrading to Webring 1.2

### ISSUE THREAD

**Issue by justinmayer** [pelican-plugins/webring#11]
The commit (https://github.com/pelican-plugins/webring/commit/9e35c8e69ce80e2e25a28cf95a9a412e1251de25) intended to implement #6 seems to be causing an error for me:
```python
$ pelican --debug -s publishconf.py

[…]
  File "~/projects/justinmayer/themes/pure/templates/index.html", line 37, in block "content"
    {% include 'webring.html' %}
  File "~/projects/justinmayer/themes/pure/templates/webring.html", line 14, in top-level template code
    <small class="date">{{ article.date|strftime('%d %B %Y') }}</small>
  File "~/projects/pelican/pelican/utils.py", line 121, in __call__
    formatted = strftime(date, date_format)
  File "~/projects/pelican/pelican/utils.py", line 78, in strftime
    formatted = date.strftime(candidate)
AttributeError: 'str' object has no attribute 'strftime'
```

The relevant line in my `webring.html` template is:
```jinja2
<small class="date">{{ article.date|strftime('%d %B %Y') }}</small>
```
… which appears to be consistent with the instructions in the current README.

Reverting to Webring 1.0 resolves the problem. The commit in question clearly intended for the changes to be backward-compatible, but for some reason that has not been the case for me.

@davidag: Any thoughts on how to resolve this?

**Comment by justinmayer** [comment]
@davidag: Hey David. Just thought I'd follow up and see if you have a moment to review this potential bug. Even just a cursory review would be most helpful. What do you think? 🙏

**Comment by davidag** [comment]
Sorry @justinmayer, I’ll look into it! Thx for the heads-up 😅

**Comment by justinmayer** [comment]
I just tested the 1.3 release, and your changes appear to have resolved the problem. Many thanks for fixing that error. Much appreciated! 😁

**Comment by davidag** [comment]
Thank you for reporting! 💯
