### ISSUE TITLE
Failed to load articles in github codespace or gitpod

### ISSUE THREAD

**Issue by hillerliao** [pelican-plugins/webring#20]
I installed webring and my related settings are here hillerliao.github.io/pelicanconf.py at main · hillerliao/hillerliao.github.io  https://github.com/hillerliao/hillerliao.github.io/blob/main/pelicanconf.py 

Everything is ok when running  on my local developing environment. But when running in gitpod or github codespaces, the  post list is empty.  https://zhihai.me/talk is the page for me to host the posts from rss feeds.

**Comment by justinmayer** [comment]
Hi @hillerliao. Would you please provide more information in the issue description? Otherwise we have no choice but to close this issue.

**Comment by davidag** [comment]
@hillerliao It looks like you're not installing the `pelican-webring` package. It should be added to your [requirements.txt](https://github.com/hillerliao/hillerliao.github.io/blob/main/requirements.txt)
