### ISSUE TITLE
Extract more information from feed items

### ISSUE THREAD

**Issue by davidag** [pelican-plugins/webring#6]
As suggested by @ashwinvis it would be interesting to extract more information from feeds, if available.

At the very least, attributes explicitly supported by [feedgenerator](https://github.com/getpelican/feedgenerator) (the module used by Pelican to create its own feeds) should be extracted.

A list of the attributes the method  [SyndicateFeed.add_item()](https://github.com/getpelican/feedgenerator/blob/master/feedgenerator/django/utils/feedgenerator.py#L117) accepts is (in green, what webring currently supports; in red, what it doesn't):
- `title` :heavy_check_mark: 
- `link` :heavy_check_mark: 
- `description` :heavy_check_mark: 
- `content` :x: _(same name in and Atom, not available in RSS)_
- `author_email` :x: _(part of 'author' in RSS, as 'author.email' in Atom)_
- `author_name` :x: _(part of 'author' or 'dc:creator' in RSS, as 'author.name' in Atom)_
- `author_link` :x: _(as 'author.uri' in Atom, not available in RSS)_
- `pubdate` :heavy_check_mark:
- `updateddate` :x: _(same name in Atom, 'updated' in RSS)_
- `comments` :x: _(same name in RSS)_
- `unique_id` :x: _('guid' in RSS, 'id' in Atom)_
- `ttl` :x: _(same name in RSS)_
- `enclosures` :x: _([used for multimedia](https://en.wikipedia.org/wiki/RSS_enclosure))_
- `category` :x: _(multiple elements, same name in RSS and Atom)_
- `item_copyright` :x: _('rights' in Atom)_

**Comment by ashwinvis** [comment]
As a side note, the planet plugin right now does a better job in truncating and sanitizing the summary:

https://github.com/ashwinvis/pelican-planet/blob/e1327fca0c7a89a903cca1a99485ba9c0aeed0b4/pelican_planet/utils.py#L28-L55

Feel free to use it :)

**Comment by davidag** [comment]
@ashwinvis thank you for the information! It looks quite more powerful, maybe some new option is required to customize the truncation behavior. I'll report a new issue to follow this.

**Comment by davidag** [comment]
This issue should be solved with commit 9e35c8e

@ashwinvis I hope this is useful for you! Thanks again for letting me know.
